# Generated by Django 2.0.5 on 2018-09-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '003_mutualfund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutualfund',
            old_name='acquired_date',
            new_name='acquiredm_date',
        ),
        migrations.RenameField(
            model_name='mutualfund',
            old_name='acquired_value',
            new_name='acquiredm_value',
        ),
        migrations.RenameField(
            model_name='mutualfund',
            old_name='recent_date',
            new_name='recentm_date',
        ),
        migrations.RenameField(
            model_name='mutualfund',
            old_name='recent_value',
            new_name='recentm_value',
        ),
    ]
